// Huddle Up — Passing Game playbook data
// Internal route/position keys (X, B, Y, A, F, Q) are just geometry lookups for the
// field diagram — nothing user-facing ever shows these letters. See ROLE_MAP in app.js
// for how each key maps to a plain-language role (Wide Receiver, Slot Receiver, etc.)

const RULES = [
  "The wide receiver and slot receiver on the same side of the field always line up together — wherever one goes, the other's right there.",
  "The QB can always throw the ball away to save a play, but it has to cross the line of scrimmage first. No spiking it behind the line.",
  "This offense runs the exact same plays out of 5 different looks: Spread, Snug, Rio (trips right), Leo (trips left), and Stack. Same play, different furniture.",
];

const PLAYS = [
  {
    id: "basics",
    unit: 0,
    unitName: "Get Oriented",
    category: "intro",
    name: "Playbook Basics",
    nickname: "Learn the code before you sling it",
    icon: "📘",
    formation: "normal",
    gist: "Before we start chucking the rock around, let's get the ground rules straight. This playbook is way simpler once you know a few tricks the coaches built in.",
    facts: RULES,
    assignments: [],
    readKey: "There's no read here — just the rules of the road. Every play in this book plays by them.",
    quiz: [
      {
        q: "True or false: the wide receiver and slot receiver on the same side of the field always line up together.",
        options: ["True", "False"],
        correct: 0,
        why: "They're always paired up on the same side — tag-team partners.",
      },
      {
        q: "The QB wants to throw the ball away. What's the rule?",
        options: [
          "Can chuck it anywhere, even behind the line",
          "Has to throw it past the line of scrimmage",
          "Only allowed to throw it to the running back",
          "Not allowed to throw it away at all",
        ],
        correct: 1,
        why: "Gotta get it past the line of scrimmage — otherwise it's intentional grounding.",
      },
      {
        q: "What does a \"Rio\" call mean?",
        options: [
          "Trips formation to the right",
          "Trips formation to the left",
          "Empty backfield, no running back",
          "Everybody goes deep, no matter what",
        ],
        correct: 0,
        why: "Rio = trips right. Leo = trips left. Same routes, just bunched to a different side.",
      },
    ],
  },

  // ---------------- UNIT 1: QUICK GAME ----------------
  {
    id: "maine",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Maine",
    nickname: "The safety valve",
    icon: "⚡",
    formation: "normal",
    gist: "Maine is your quick-rhythm, get-it-out-fast play. Everybody runs a hitch — stop, sit down, look back at the QB. Basically \"catch it and go\" football.",
    assignments: [
      { abbrev: "WR", role: "Wide Receivers (both sides)", text: "Run it out to 7 yards, plant, and sit down facing the QB. Break back toward the middle of the field." },
      { abbrev: "SR", role: "Slot Receivers (both sides)", text: "Same idea, just 3 yards deep. Get inside leverage and hang out right in front of the linebacker." },
      { abbrev: "RB", role: "Running Back", text: "Stay in and pass protect. Make the call — Lobo or Robin — to set it up." },
    ],
    readKey: "QB takes a quick shotgun step (or a bigger drop under center) and reads one side, inside-out. If the linebacker flies out toward the sideline, the slot receiver's sitting open underneath — throw it inside. If he sits underneath, the wide receiver's hitch is open over his head — throw it outside.",
    routes: [
      { pos: "X", type: "hitch", dir: -1, depth: 7 },
      { pos: "B", type: "hitch", dir: -1, depth: 3 },
      { pos: "Y", type: "hitch", dir: 1, depth: 7 },
      { pos: "A", type: "hitch", dir: 1, depth: 3 },
    ],
    quiz: [
      {
        q: "How do the wide receivers move in Maine?",
        options: ["They run 7 yards, stop, and sit down facing the QB", "They run a slant across the middle", "They stay in and block", "They sprint deep and never look back"],
        correct: 0,
        why: "Both wide receivers hitch up at 7 yards and look back for it.",
      },
      {
        q: "What do the slot receivers do in Maine?",
        options: ["Run a 3-yard hitch, working in front of the linebacker", "Run a deep post", "Block the edge", "Run a wheel route"],
        correct: 0,
        why: "Slot receivers run the same hitch idea, just shorter — 3 yards instead of 7.",
      },
      {
        q: "The linebacker flies out toward the sideline. Who's open?",
        options: ["The slot receiver underneath him", "The wide receiver on that side", "The running back", "Nobody, throw it away"],
        correct: 0,
        why: "When the backer widens out toward the wide receiver, he leaves the slot receiver open underneath.",
      },
    ],
  },
  {
    id: "boston",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Boston",
    nickname: "Slant-and-out special",
    icon: "⚡",
    formation: "normal",
    gist: "Boston is a lightning-fast in-or-out combo. The wide receivers slant inside while the slot receivers pop straight out to the sideline. Whichever one the linebacker leaves open gets the ball.",
    assignments: [
      { abbrev: "WR", role: "Wide Receivers (both sides)", text: "Quick slant — release inside of the corner and cut across on your third step." },
      { abbrev: "SR", role: "Slot Receivers (both sides)", text: "Just get out. 2-3 yards, stick it to the sideline. Fastest route in the whole book." },
      { abbrev: "RB", role: "Running Back", text: "Protect the QB. Lobo or Robin call." },
    ],
    readKey: "One-step game — this ball is coming out FAST. QB reads slot-to-wide. If the linebacker widens out to cover the flat, the wide receiver's slant is coming open behind him. If he sits or drops, hit the slot receiver's quick out in front of him.",
    routes: [
      { pos: "X", type: "slant", dir: -1, depth: 3 },
      { pos: "B", type: "out", dir: -1, depth: 3 },
      { pos: "Y", type: "slant", dir: 1, depth: 3 },
      { pos: "A", type: "out", dir: 1, depth: 3 },
    ],
    quiz: [
      {
        q: "The linebacker widens out to cover the flat route. What's open?",
        options: ["The slot receiver's quick out", "The wide receiver's slant behind him", "Nothing, throw it away", "The deep ball"],
        correct: 1,
        why: "When the backer widens to take away the slot receiver's out route, the wide receiver's slant opens up behind him.",
      },
      {
        q: "What do the slot receivers run in Boston?",
        options: ["A deep post", "A 2-3 yard quick out", "A slant across the middle", "A block"],
        correct: 1,
        why: "Slot receivers get out to the sideline as fast as possible — 2 to 3 yards, tops.",
      },
      {
        q: "How many steps does the QB take before this ball comes out?",
        options: ["1 step", "3 steps", "5 steps", "7 steps"],
        correct: 0,
        why: "Boston is a 1-step game — quickest timing in the playbook.",
      },
    ],
  },
  {
    id: "mass",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Mass",
    nickname: "Double slant",
    icon: "⚡",
    formation: "normal",
    gist: "Mass stacks two slants on top of each other on the same side. The QB just picks a side and lets the read tell him who to throw it to.",
    assignments: [
      { abbrev: "WR", role: "Wide Receivers (both sides)", text: "3-step slant. Inside release of the corner, break it in once you're past him." },
      { abbrev: "SR", role: "Slot Receivers (both sides)", text: "1-step slant — quick and shallow, inside release off the linebacker." },
      { abbrev: "RB", role: "Running Back", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "One step, pick a side. If the backer flies out to jump the wide receiver's slant, hit the slot receiver underneath him. If he sits, go over the top with the wide receiver's slant.",
    routes: [
      { pos: "X", type: "slant", dir: -1, depth: 4 },
      { pos: "B", type: "slant", dir: -1, depth: 1.5 },
      { pos: "Y", type: "slant", dir: 1, depth: 4 },
      { pos: "A", type: "slant", dir: 1, depth: 1.5 },
    ],
    quiz: [
      {
        q: "The linebacker flies out toward the wide receiver's slant. Who should get the ball?",
        options: ["The wide receiver anyway", "The slot receiver underneath", "Nobody, throw it away", "The running back"],
        correct: 1,
        why: "If the backer jumps toward the wide receiver, the slot receiver's slant opens up underneath him.",
      },
      {
        q: "What makes Mass different from Boston?",
        options: ["Mass has the wide receiver and slot receiver both running slants, just at different depths", "Mass is a run play", "Mass only has one receiver", "Mass is a deep shot play"],
        correct: 0,
        why: "Boston pairs a slant with an out. Mass pairs a slant with another, shallower slant.",
      },
      {
        q: "Does the QB read both sides of the field on Mass?",
        options: ["Yes, always both sides", "No, he picks one side and reads it", "No, it's a pre-determined throw", "Only if the safety blitzes"],
        correct: 1,
        why: "The QB picks a side pre-snap or post-snap and just reads that side's slant combo.",
      },
    ],
  },
  {
    id: "vermont",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Vermont",
    nickname: "Fade-and-out",
    icon: "⚡",
    formation: "normal",
    gist: "Vermont pairs a fade up the sideline with a speed out underneath. Classic \"take the top off, or take what they give you\" combo.",
    assignments: [
      { abbrev: "WR", role: "Wide Receivers (both sides)", text: "Release outside of the corner and run straight down the numbers — fade route." },
      { abbrev: "SR", role: "Slot Receivers (both sides)", text: "Quick 2-3 step speed out. Stay under 5 yards, get it and go." },
      { abbrev: "RB", role: "Running Back", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "Read the corner. If he sits on the short stuff, throw the wide receiver's fade right over his head. If he bails deep with the receiver, dump it underneath to the slot receiver's speed out.",
    routes: [
      { pos: "X", type: "fade", dir: -1 },
      { pos: "B", type: "out", dir: -1, depth: 3, quick: true },
      { pos: "Y", type: "fade", dir: 1 },
      { pos: "A", type: "out", dir: 1, depth: 3, quick: true },
    ],
    quiz: [
      {
        q: "The corner sits on the short route. What's the call?",
        options: ["Throw the wide receiver's fade over him", "Throw the slot receiver's speed out anyway", "Hand it off", "Take a sack"],
        correct: 0,
        why: "If the corner stays up on the short stuff, he's got nobody behind him for the fade.",
      },
      {
        q: "How do the wide receivers move in Vermont?",
        options: ["Release outside and run straight down the numbers on a fade", "Cut inside on a slant", "Run a quick out", "Block the corner"],
        correct: 0,
        why: "Wide receivers release outside and run the fade straight down the numbers.",
      },
      {
        q: "If the corner bails deep with the receiver, where should the ball go?",
        options: ["Still throw the fade", "The slot receiver's speed out underneath", "Throw it away", "Scramble"],
        correct: 1,
        why: "If he bails deep, he's leaving the short area open for the speed out.",
      },
    ],
  },
  {
    id: "connecticut",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Connecticut",
    nickname: "Seam and slant",
    icon: "⚡",
    formation: "normal",
    gist: "The slot receivers run a seam straight up the hash while the wide receivers cut underneath on a slant. It's a vertical stretch on the linebacker — he can't cover both.",
    assignments: [
      { abbrev: "WR", role: "Wide Receivers (both sides)", text: "3-step slant." },
      { abbrev: "SR", role: "Slot Receivers (both sides)", text: "Seam route, right up the hash. Just run." },
      { abbrev: "RB", role: "Running Back", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "Read seam-to-slant. If the linebacker sits, the slot receiver's seam route goes right over his head. If he runs with the seam, the wide receiver's slant is sitting open underneath.",
    routes: [
      { pos: "X", type: "slant", dir: -1, depth: 4 },
      { pos: "B", type: "seam", dir: -1 },
      { pos: "Y", type: "slant", dir: 1, depth: 4 },
      { pos: "A", type: "seam", dir: 1 },
    ],
    quiz: [
      {
        q: "What do the slot receivers do in Connecticut?",
        options: ["Run a seam route, straight up the hash", "Run a slant across the middle", "Run a fade up the sideline", "Block"],
        correct: 0,
        why: "Slot receivers run the seam, straight up the hash marks.",
      },
      {
        q: "The linebacker sits and doesn't carry the seam route. What's open?",
        options: ["The wide receiver's slant", "The slot receiver's seam, right over his head", "Nothing", "The screen"],
        correct: 1,
        why: "If he sits, he's not carrying the seam vertically — throw it right over him.",
      },
      {
        q: "If the linebacker runs with the seam route, what opens up?",
        options: ["The wide receiver's slant underneath him", "Another seam route", "A deep post", "Nothing changes"],
        correct: 0,
        why: "Once the backer takes off with the seam, the wide receiver's slant sits open in the space he vacated.",
      },
    ],
  },

  // ---------------- UNIT 2: SHOT PLAYS ----------------
  {
    id: "miami",
    unit: 2,
    unitName: "Shot Plays",
    category: "long",
    name: "Miami",
    nickname: "Shot to the post",
    icon: "🚀",
    formation: "normal",
    gist: "Miami's a bigger shot play. A dig-and-post combo on one side, a hitch-and-corner combo on the other. QB reads the safeties to find the soft spot in the coverage.",
    assignments: [
      { abbrev: "WR", role: "Wide Receiver (dig side)", text: "Shallow in-cut, 3-5 yards, square it in across the middle." },
      { abbrev: "SR", role: "Slot Receiver (post side)", text: "Post route — 7 yards, then bend it toward the goalposts at 45 degrees." },
      { abbrev: "WR", role: "Wide Receiver (checkdown side)", text: "Just a hitch, 3 yards. The checkdown, nothing fancy." },
      { abbrev: "SR", role: "Slot Receiver (corner side)", text: "Go 7 yards vertical, then break it toward the pylon — corner route." },
      { abbrev: "RB", role: "Running Back", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "Bigger drop this time — 3 steps from gun, 5 under center. Read the safeties. Two deep? Work the dig-and-post combo — the wide receiver's dig or the slot receiver's post. One deep? Work the corner from the other slot receiver, with the checkdown wide receiver's hitch always there as a safety valve.",
    routes: [
      { pos: "X", type: "dig", dir: -1 },
      { pos: "B", type: "post", dir: -1 },
      { pos: "Y", type: "hitch", dir: 1, depth: 3 },
      { pos: "A", type: "corner", dir: 1 },
    ],
    quiz: [
      {
        q: "Two safeties are hanging deep. Which combo does the QB lean on?",
        options: ["The wide receiver's dig and the slot receiver's post", "The corner route by itself", "Always check it down", "Hand it off"],
        correct: 0,
        why: "Two-high safeties means the QB works the dig-and-post side of the formation.",
      },
      {
        q: "What does the post-side slot receiver do?",
        options: ["Goes 7 yards then bends it toward the goalposts at 45 degrees", "Sits down at 3 yards", "Runs a fade up the sideline", "Blocks the edge"],
        correct: 0,
        why: "That slot receiver runs 7 yards then bends it toward the goalposts — the post.",
      },
      {
        q: "Which receiver is just running the checkdown on this play?",
        options: ["The wide receiver on the hitch", "The slot receiver on the post", "The slot receiver on the corner", "The wide receiver on the dig"],
        correct: 0,
        why: "That wide receiver just runs a simple 3-yard hitch — the safety valve if the shot isn't there.",
      },
    ],
  },
  {
    id: "crook",
    unit: 2,
    unitName: "Shot Plays",
    category: "long",
    name: "Crook",
    nickname: "Wheel route trick",
    icon: "🚀",
    formation: "normal",
    gist: "Crook is a shot play with a sneaky wheel route baked in. Fake the block, sneak up the sideline, and hope nobody's watching.",
    assignments: [
      { abbrev: "WR", role: "Wide Receivers (both sides)", text: "5-yard hitch." },
      { abbrev: "SR", role: "Slot Receiver (corner side)", text: "7-yard vertical release, then bend it toward the pylon — corner." },
      { abbrev: "SR", role: "Slot Receiver (wheel side)", text: "Sell the block on the corner first, then sneak up the sideline on a wheel route. Don't look for it until you're 10 yards up the field." },
      { abbrev: "RB", role: "Running Back", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "Take the deep combo on the left if you need the extra yardage. Or fake it to the wide receiver's hitch on the right and throw the slot receiver's wheel route instead.",
    routes: [
      { pos: "X", type: "hitch", dir: -1, depth: 5 },
      { pos: "B", type: "corner", dir: -1 },
      { pos: "Y", type: "hitch", dir: 1, depth: 5 },
      { pos: "A", type: "wheel", dir: 1 },
    ],
    quiz: [
      {
        q: "What's the trick in Crook?",
        options: ["A hidden ball trick", "The slot receiver fakes a block, then sneaks a wheel route up the sideline", "A wide receiver throws the ball", "It's actually a run play"],
        correct: 1,
        why: "That slot receiver fakes like he's blocking the corner, then releases up the sideline on a wheel — that's the gadget.",
      },
      {
        q: "When should the wheel-route slot receiver look back for the ball?",
        options: ["Immediately off the line", "Not until he's about 10 yards upfield", "Never, it's a decoy", "As soon as he beats the corner"],
        correct: 1,
        why: "Look too early and you'll slow down or tip the route — sell the fake, then find the ball.",
      },
      {
        q: "If the defense is playing tight and you need a chunk play, which combo does the QB lean on?",
        options: ["The deep combo on the left", "The running back dump-off", "Always the wheel route", "The wide receiver's hitch"],
        correct: 0,
        why: "The deep left combo is the called shot when you need more yardage.",
      },
    ],
  },
  {
    id: "virginia",
    unit: 2,
    unitName: "Shot Plays",
    category: "long",
    name: "Virginia",
    nickname: "Four verticals, pick your guy",
    icon: "🚀",
    formation: "normal",
    gist: "Everybody just runs. Virginia is four verticals — the QB's whole job is finding the best matchup and letting it fly deep.",
    assignments: [
      { abbrev: "WR", role: "Wide Receivers (both sides)", text: "Outside release, run and look for the ball after 10-15 yards." },
      { abbrev: "SR", role: "Slot Receivers (both sides)", text: "Inside release toward the hash marks, look for the ball after 10-15 yards." },
      { abbrev: "RB", role: "Running Back", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "One high safety? Work the wide receivers. Two high safeties? Work the slot receivers. Either way — find the best matchup and throw it up.",
    routes: [
      { pos: "X", type: "go", dir: -1 },
      { pos: "B", type: "seam", dir: -1 },
      { pos: "Y", type: "go", dir: 1 },
      { pos: "A", type: "seam", dir: 1 },
    ],
    quiz: [
      {
        q: "There's one high safety. Who does the QB work?",
        options: ["The wide receivers", "The slot receivers", "Only the running back", "Nobody, it's a run check"],
        correct: 0,
        why: "One high safety means he can't help outside — that's where the QB should look.",
      },
      {
        q: "There are two deep safeties. Who does the QB work?",
        options: ["The wide receivers", "The slot receivers", "He should throw it away", "The running back only"],
        correct: 1,
        why: "With two safeties splitting the field, the slot receivers' seams have the better one-on-one.",
      },
      {
        q: "How many receivers are running vertical routes on this play?",
        options: ["Two", "Three", "Four", "One"],
        correct: 2,
        why: "It's called four verticals for a reason — both wide receivers and both slot receivers are all going.",
      },
    ],
  },

  // ---------------- UNIT 3: TRIPS & TRICK PLAYS ----------------
  {
    id: "verizon",
    unit: 3,
    unitName: "Trips & Trick Plays",
    category: "trips",
    name: "Verizon",
    nickname: "Four verticals out of trips",
    icon: "🎯",
    formation: "tripsRight",
    gist: "Same idea as Virginia, but out of a bunched-up trips look — three receivers stacked to one side. Everybody still just runs.",
    assignments: [
      { abbrev: "WR", role: "Backside Wide Receiver", text: "Alone on the backside. Outside release, go get it after 10-15 yards." },
      { abbrev: "SR", role: "Inside Slot Receiver", text: "Release toward the middle of the field, then turn it up straight once you're there." },
      { abbrev: "SR", role: "Middle Slot Receiver", text: "Release toward the hash, then turn it up straight once you get there." },
      { abbrev: "WR", role: "Trips Wide Receiver", text: "Outside receiver in the trips bunch — outside release, go get it deep." },
      { abbrev: "RB", role: "Running Back", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "If there's a favorable one-on-one on the backside wide receiver, just throw it to him. Otherwise, read the safeties — they've got to pick who they leave open.",
    routes: [
      { pos: "X", type: "go", dir: -1 },
      { pos: "B", type: "seam", dir: 1 },
      { pos: "A", type: "seam", dir: 1 },
      { pos: "Y", type: "go", dir: 1 },
    ],
    quiz: [
      {
        q: "The backside wide receiver is singled up with a great matchup. What does the QB do?",
        options: ["Ignore it and work the trips side", "Just throw it to him", "Automatically throw it away", "Check to a run"],
        correct: 1,
        why: "A favorable 1-on-1 on the lone receiver is money — take it.",
      },
      {
        q: "How is Verizon different from Virginia?",
        options: ["It's a run play", "It's four verticals out of a trips (bunched) formation", "It only has two receivers", "There's no QB read"],
        correct: 1,
        why: "Same vertical concept, just packaged out of trips instead of a balanced formation.",
      },
      {
        q: "On Verizon, what do the safeties have to do?",
        options: ["Nothing, they're not involved", "Choose who they're willing to leave open", "Always double the backside receiver", "Blitz every time"],
        correct: 1,
        why: "With four guys going deep, the safeties can't cover everybody — someone's getting left open.",
      },
    ],
  },
  {
    id: "pacific",
    unit: 3,
    unitName: "Trips & Trick Plays",
    category: "trips",
    name: "Pacific",
    nickname: "Three levels, pick your poison",
    icon: "🎯",
    formation: "tripsRight",
    gist: "Pacific stacks three different depths on the same side — short, medium, deep — so there's always something open no matter what the defense gives up.",
    assignments: [
      { abbrev: "WR", role: "Backside Wide Receiver", text: "Alone on the backside. Dig across the middle at 10 yards." },
      { abbrev: "SR", role: "Inside Slot Receiver", text: "The quickest route on the play — a 2-3 yard out. Get it out fast." },
      { abbrev: "SR", role: "Middle Slot Receiver", text: "7-yard vertical release, then bend it to the pylon — corner." },
      { abbrev: "WR", role: "Trips Wide Receiver", text: "Vertical release, look for the ball deep." },
      { abbrev: "RB", role: "Running Back", text: "Pass protect. Lobo or Robin call — could sprint out too." },
    ],
    readKey: "Three levels stacked on top of each other: something short, something in the middle, and a shot deep. Take whatever the defense gives up, top to bottom.",
    routes: [
      { pos: "X", type: "dig", dir: -1 },
      { pos: "B", type: "out", dir: 1, depth: 3, quick: true },
      { pos: "A", type: "corner", dir: 1 },
      { pos: "Y", type: "go", dir: 1 },
    ],
    quiz: [
      {
        q: "What's the whole idea behind Pacific?",
        options: ["Everybody blocks", "Stacking three depths so something's always open", "It's a screen pass", "Only the deep ball matters"],
        correct: 1,
        why: "Short, medium, deep — the defense can't take away all three levels at once.",
      },
      {
        q: "Which receiver runs the fastest route out on Pacific?",
        options: ["The backside wide receiver", "The inside slot receiver", "The middle slot receiver", "The trips wide receiver"],
        correct: 1,
        why: "The inside slot receiver's route is only 2-3 yards — it's designed to get out in a hurry.",
      },
      {
        q: "Where does the backside wide receiver line up on Pacific?",
        options: ["Bunched with the trips", "Alone, away from the trips bunch", "In the backfield", "Next to the tackle"],
        correct: 1,
        why: "The backside wide receiver is the lone guy away from the trips bunch.",
      },
    ],
  },
  {
    id: "torch",
    unit: 3,
    unitName: "Trips & Trick Plays",
    category: "trips",
    name: "Torch",
    nickname: "The old razzle-dazzle",
    icon: "🎭",
    formation: "normal",
    gist: "Torch is the trick play of the bunch. It looks like a run to the slot, but the running back is actually about to throw it downfield. Total gadget football.",
    assignments: [
      { abbrev: "WR", role: "Wide Receiver (dig side)", text: "10-yard square-in — a dig route." },
      { abbrev: "SR", role: "Slot Receiver (crossing side)", text: "5-yard crossing route. Also doubles as the backup safety valve for the running back." },
      { abbrev: "WR", role: "Wide Receiver (stalk-and-go side)", text: "Stalk block first — sell it like a run — then release deep once the DB bites on the fake." },
      { abbrev: "SR", role: "Slot Receiver (seal side)", text: "Seal the edge. Keep the defensive end from crashing outside and blowing the whole thing up." },
      { abbrev: "RB", role: "Running Back — Passer", text: "You're the passer now. Get depth, square your shoulders, and sell the run before you even think about throwing. If nobody's open downfield, tuck it and run — or just chuck it away." },
    ],
    readKey: "The QB options it to the running back. From there, the running back is running the whole show — sell the run, then find the stalk-and-go wide receiver or the edge-sealing slot receiver downfield.",
    routes: [
      { pos: "X", type: "dig", dir: -1 },
      { pos: "B", type: "cross", dir: -1 },
      { pos: "Y", type: "go", dir: 1, stalk: true },
      { pos: "A", type: "seal", dir: 1 },
      { pos: "F", type: "loopFlat", dir: 1 },
    ],
    quiz: [
      {
        q: "Who actually throws the ball on Torch?",
        options: ["The QB", "The running back", "The wide receiver", "Nobody, it's a designed run"],
        correct: 1,
        why: "The QB options it to the running back, who becomes the passer once he clears the line.",
      },
      {
        q: "What does the stalk-and-go wide receiver need to do before releasing on his route?",
        options: ["Nothing, just run", "Sell the block like it's a real run play first", "Line up in the backfield", "Throw a block on the safety only"],
        correct: 1,
        why: "He has to stalk block and sell the fake before the DB will bite and open up the route.",
      },
      {
        q: "If nobody's open, what's the running back's job?",
        options: ["Force a throw no matter what", "Tuck it and run, or throw it away", "Take a knee", "Lateral it to the wide receiver"],
        correct: 1,
        why: "Same rule as always — if it's not there, protect the ball. Run it or chuck it away.",
      },
    ],
  },
];
