// Huddle Up — Passing Game playbook data
// Route shorthand: pos = position label, type = route shape, dir = -1 (left) / +1 (right)

const RULES = [
  "X and B always line up together on one side. Y and A always line up together on the other side. They're tag-team partners — wherever one goes, the other's right there.",
  "The QB can always throw the ball away to save a play, but it has to cross the line of scrimmage first. No spiking it behind the line.",
  "This offense runs the exact same plays out of 5 different looks: Spread, Snug, Rio (trips right), Leo (trips left), and Stack. Same play, different furniture.",
];

const PLAYS = [
  {
    id: "basics",
    unit: 0,
    unitName: "Get Oriented",
    category: "intro",
    name: "Playbook Basics",
    nickname: "Learn the code before you sling it",
    icon: "📘",
    formation: "normal",
    gist: "Before we start chucking the rock around, let's get the ground rules straight. This playbook is way simpler once you know a few tricks the coaches built in.",
    facts: RULES,
    assignments: [],
    readKey: "There's no read here — just the rules of the road. Every play in this book plays by them.",
    quiz: [
      {
        q: "True or false: X and B always line up on the same side of the field.",
        options: ["True", "False"],
        correct: 0,
        why: "X and B are always paired up on one side. Y and A pair up on the other.",
      },
      {
        q: "The QB wants to throw the ball away. What's the rule?",
        options: [
          "Can chuck it anywhere, even behind the line",
          "Has to throw it past the line of scrimmage",
          "Only allowed to throw it to the RB",
          "Not allowed to throw it away at all",
        ],
        correct: 1,
        why: "Gotta get it past the line of scrimmage — otherwise it's intentional grounding.",
      },
      {
        q: "What does a \"Rio\" call mean?",
        options: [
          "Trips formation to the right",
          "Trips formation to the left",
          "Empty backfield, no RB",
          "Everybody goes deep, no matter what",
        ],
        correct: 0,
        why: "Rio = trips right. Leo = trips left. Same routes, just bunched to a different side.",
      },
    ],
  },

  // ---------------- UNIT 1: QUICK GAME ----------------
  {
    id: "maine",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Maine",
    nickname: "The safety valve",
    icon: "⚡",
    formation: "normal",
    gist: "Maine is your quick-rhythm, get-it-out-fast play. Everybody runs a hitch — stop, sit down, look back at the QB. Basically \"catch it and go\" football.",
    assignments: [
      { pos: "X", text: "Run it out to 7 yards, plant, and sit down facing the QB. Break back toward the middle of the field." },
      { pos: "B", text: "Same idea, just 3 yards deep. Get inside leverage and hang out right in front of the linebacker." },
      { pos: "Y", text: "Mirror of X — 7 yards, sit down, look back for it." },
      { pos: "A", text: "Mirror of B — quick 3-yard hitch, inside release." },
      { pos: "F", text: "Stay in and pass protect. Make the call — Lobo or Robin — to set it up." },
    ],
    readKey: "QB takes a quick shotgun step (or a bigger drop under center) and reads one side, outside-in. If the linebacker flies out to jump the short route, throw it over his head to the outside guy. If he just sits there, dump it underneath to whoever's in front of him.",
    routes: [
      { pos: "X", type: "hitch", dir: -1, depth: 7 },
      { pos: "B", type: "hitch", dir: -1, depth: 3 },
      { pos: "Y", type: "hitch", dir: 1, depth: 7 },
      { pos: "A", type: "hitch", dir: 1, depth: 3 },
    ],
    quiz: [
      {
        q: "In Maine, what's X's job?",
        options: ["Hitch at 7 yards, sit down and look back", "Run deep and never look back", "Block the edge rusher", "Run a slant across the middle"],
        correct: 0,
        why: "X (and Y on the other side) run the deeper 7-yard hitch.",
      },
      {
        q: "The outside linebacker flies out to jump the short route. What should the QB do?",
        options: ["Force it to the guy he's covering anyway", "Throw the outside hitch over his head", "Take off and run it himself", "Automatically throw it away"],
        correct: 1,
        why: "If the backer bites on the short guy, the outside hitch is wide open behind him.",
      },
      {
        q: "True or false: B and A run basically the same route as X and Y, just shorter and closer to the ball.",
        options: ["True", "False"],
        correct: 0,
        why: "Same hitch concept for everybody — B/A just sit down at 3 yards instead of 7.",
      },
    ],
  },
  {
    id: "boston",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Boston",
    nickname: "Slant-and-out special",
    icon: "⚡",
    formation: "normal",
    gist: "Boston is a lightning-fast in-or-out combo. The outside guys slant inside while the inside guys pop straight out to the sideline. Whichever one the linebacker leaves open gets the ball.",
    assignments: [
      { pos: "X", text: "Quick slant — release inside of the corner and cut across on your third step." },
      { pos: "B", text: "Just get out. 2-3 yards, stick it to the sideline. Fastest route in the whole book." },
      { pos: "Y", text: "Same slant as X, mirrored." },
      { pos: "A", text: "Same quick out as B, mirrored." },
      { pos: "F", text: "Protect the QB. Lobo or Robin call." },
    ],
    readKey: "One-step game — this ball is coming out FAST. QB reads inside-to-outside. If the linebacker widens out to cover the flat, the slant's coming open behind him. If he sits or drops, hit the quick out in front of him.",
    routes: [
      { pos: "X", type: "slant", dir: -1, depth: 3 },
      { pos: "B", type: "out", dir: -1, depth: 3 },
      { pos: "Y", type: "slant", dir: 1, depth: 3 },
      { pos: "A", type: "out", dir: 1, depth: 3 },
    ],
    quiz: [
      {
        q: "The linebacker widens out to cover the flat route. What's open?",
        options: ["The quick out", "The slant behind him", "Nothing, throw it away", "The deep ball"],
        correct: 1,
        why: "When the backer widens to take away the out, he leaves the slant window open behind him.",
      },
      {
        q: "What's B's route in Boston?",
        options: ["A deep post", "A 2-3 yard quick out", "A slant across the middle", "A block"],
        correct: 1,
        why: "B just gets out to the sideline as fast as possible — 2 to 3 yards, tops.",
      },
      {
        q: "How many steps does the QB take before this ball comes out?",
        options: ["1 step", "3 steps", "5 steps", "7 steps"],
        correct: 0,
        why: "Boston is a 1-step game — quickest timing in the playbook.",
      },
    ],
  },
  {
    id: "mass",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Mass",
    nickname: "Double slant",
    icon: "⚡",
    formation: "normal",
    gist: "Mass stacks two slants on top of each other on the same side. The QB just picks a side and lets the read tell him who to throw it to.",
    assignments: [
      { pos: "X", text: "3-step slant. Inside release of the corner, break it in once you're past him." },
      { pos: "B", text: "1-step slant — quick and shallow, inside release off the linebacker." },
      { pos: "Y", text: "Mirror of X." },
      { pos: "A", text: "Mirror of B." },
      { pos: "F", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "One step, pick a side. If the backer flies out to jump the outside slant, hit the inside guy underneath him. If he sits, go over the top with the outside slant.",
    routes: [
      { pos: "X", type: "slant", dir: -1, depth: 4 },
      { pos: "B", type: "slant", dir: -1, depth: 1.5 },
      { pos: "Y", type: "slant", dir: 1, depth: 4 },
      { pos: "A", type: "slant", dir: 1, depth: 1.5 },
    ],
    quiz: [
      {
        q: "The linebacker flies out toward the outside slant. Who should get the ball?",
        options: ["The outside guy (X or Y)", "The inside guy (A or B)", "Nobody, throw it away", "The RB"],
        correct: 1,
        why: "If the backer jumps outside, the inside slant opens up underneath him.",
      },
      {
        q: "What makes Mass different from Boston?",
        options: ["Mass has two slants stacked on one side instead of a slant/out combo", "Mass is a run play", "Mass only has one receiver", "Mass is a deep shot play"],
        correct: 0,
        why: "Boston pairs a slant with an out. Mass pairs a slant with another, shallower slant.",
      },
      {
        q: "Does the QB read both sides of the field on Mass?",
        options: ["Yes, always both sides", "No, he picks one side and reads it", "No, it's a pre-determined throw", "Only if the safety blitzes"],
        correct: 1,
        why: "The QB picks a side pre-snap or post-snap and just reads that side's slant combo.",
      },
    ],
  },
  {
    id: "vermont",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Vermont",
    nickname: "Fade-and-out",
    icon: "⚡",
    formation: "normal",
    gist: "Vermont pairs a fade up the sideline with a speed out underneath. Classic \"take the top off, or take what they give you\" combo.",
    assignments: [
      { pos: "X", text: "Release outside of the corner and run straight down the numbers — fade route." },
      { pos: "B", text: "Quick 2-3 step speed out. Stay under 5 yards, get it and go." },
      { pos: "Y", text: "Mirror of X." },
      { pos: "A", text: "Mirror of B." },
      { pos: "F", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "Read the corner. If he sits on the short stuff, throw the fade right over his head. If he bails deep with the receiver, dump it underneath on the speed out.",
    routes: [
      { pos: "X", type: "fade", dir: -1 },
      { pos: "B", type: "out", dir: -1, depth: 3, quick: true },
      { pos: "Y", type: "fade", dir: 1 },
      { pos: "A", type: "out", dir: 1, depth: 3, quick: true },
    ],
    quiz: [
      {
        q: "The corner sits on the short route. What's the call?",
        options: ["Throw the fade over him", "Throw the speed out anyway", "Hand it off", "Take a sack"],
        correct: 0,
        why: "If the corner stays up on the short stuff, he's got nobody behind him for the fade.",
      },
      {
        q: "What's X running in Vermont?",
        options: ["A slant", "A fade up the sideline", "A dig across the middle", "A screen"],
        correct: 1,
        why: "X releases outside and runs straight down the numbers — that's the fade.",
      },
      {
        q: "If the corner bails deep with the receiver, where should the ball go?",
        options: ["Still throw the fade", "The speed out underneath", "Throw it away", "Scramble"],
        correct: 1,
        why: "If he bails deep, he's leaving the short area open for the speed out.",
      },
    ],
  },
  {
    id: "connecticut",
    unit: 1,
    unitName: "Quick Game",
    category: "quick",
    name: "Connecticut",
    nickname: "Seam and slant",
    icon: "⚡",
    formation: "normal",
    gist: "One guy runs a seam straight up the hash, the other cuts underneath on a slant. It's a vertical stretch on the linebacker — he can't cover both.",
    assignments: [
      { pos: "X", text: "3-step slant." },
      { pos: "B", text: "Seam route, right up the hash. Just run." },
      { pos: "Y", text: "Mirror of X." },
      { pos: "A", text: "Mirror of B." },
      { pos: "F", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "Read seam-to-slant. If the linebacker sits, the seam route goes right over his head. If he runs with the seam guy, the slant's sitting open underneath.",
    routes: [
      { pos: "X", type: "slant", dir: -1, depth: 4 },
      { pos: "B", type: "seam", dir: -1 },
      { pos: "Y", type: "slant", dir: 1, depth: 4 },
      { pos: "A", type: "seam", dir: 1 },
    ],
    quiz: [
      {
        q: "The linebacker sits and doesn't run with the seam. What's open?",
        options: ["The slant", "The seam route over his head", "Nothing", "The screen"],
        correct: 1,
        why: "If he sits, he's not carrying the seam guy vertically — throw it right over him.",
      },
      {
        q: "If the linebacker runs with the seam route, what opens up?",
        options: ["The slant underneath him", "Another seam route", "A deep post", "Nothing changes"],
        correct: 0,
        why: "Once the backer takes off with the seam guy, the slant sits open in the space he vacated.",
      },
      {
        q: "What's the read order on Connecticut?",
        options: ["Slant to seam", "Seam to slant", "There is no read, it's pre-set", "Only reads the safety"],
        correct: 1,
        why: "QB reads seam-to-slant — vertical threat first, checkdown second.",
      },
    ],
  },

  // ---------------- UNIT 2: SHOT PLAYS ----------------
  {
    id: "miami",
    unit: 2,
    unitName: "Shot Plays",
    category: "long",
    name: "Miami",
    nickname: "Shot to the post",
    icon: "🚀",
    formation: "normal",
    gist: "Miami's a bigger shot play. Dig-and-post on one side, hitch-and-corner on the other. QB reads the safeties to find the soft spot in the coverage.",
    assignments: [
      { pos: "X", text: "Shallow in-cut, 3-5 yards, square it in across the middle." },
      { pos: "B", text: "Post route — 7 yards, then bend it toward the goalposts at 45 degrees." },
      { pos: "Y", text: "Just a hitch, 3 yards. The checkdown, nothing fancy." },
      { pos: "A", text: "Go 7 yards vertical, then break it toward the pylon — corner route." },
      { pos: "F", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "Bigger drop this time — 3 steps from gun, 5 under center. Read the safeties: two deep, work the dig/corner side. One deep, work the post/corner side.",
    routes: [
      { pos: "X", type: "dig", dir: -1 },
      { pos: "B", type: "post", dir: -1 },
      { pos: "Y", type: "hitch", dir: 1, depth: 3 },
      { pos: "A", type: "corner", dir: 1 },
    ],
    quiz: [
      {
        q: "Two safeties are deep. What side should the QB work?",
        options: ["The dig/corner side", "The post/corner side", "Always throw the hitch", "Check it down every time"],
        correct: 0,
        why: "Two-high safeties means the QB works the X/A (dig/corner) matchup.",
      },
      {
        q: "What's B running?",
        options: ["A hitch", "A post route", "A wheel route", "A block"],
        correct: 1,
        why: "B runs 7 yards then bends it toward the goalposts — that's the post.",
      },
      {
        q: "Is Y's route the exciting one on this play?",
        options: ["Yes, Y runs the deepest route", "No, Y just runs a short checkdown hitch", "Y is a blocker", "Y runs the post"],
        correct: 1,
        why: "Y just runs a simple 3-yard hitch — the safety valve if the shot isn't there.",
      },
    ],
  },
  {
    id: "crook",
    unit: 2,
    unitName: "Shot Plays",
    category: "long",
    name: "Crook",
    nickname: "Wheel route trick",
    icon: "🚀",
    formation: "normal",
    gist: "Crook is a shot play with a sneaky wheel route baked in. Fake the block, sneak up the sideline, and hope nobody's watching.",
    assignments: [
      { pos: "X", text: "5-yard hitch." },
      { pos: "B", text: "7-yard vertical release, then bend it toward the pylon — corner." },
      { pos: "Y", text: "5-yard hitch, mirrored." },
      { pos: "A", text: "Sell the block on the corner first, then sneak up the sideline on a wheel route. Don't look for it until you're 10 yards up the field." },
      { pos: "F", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "Take the deep combo on the left if you need the extra yardage. Or fake it to the hitch guy on the right and throw the wheel route instead.",
    routes: [
      { pos: "X", type: "hitch", dir: -1, depth: 5 },
      { pos: "B", type: "corner", dir: -1 },
      { pos: "Y", type: "hitch", dir: 1, depth: 5 },
      { pos: "A", type: "wheel", dir: 1 },
    ],
    quiz: [
      {
        q: "What's the trick in Crook?",
        options: ["A hidden ball trick", "A's wheel route after selling a block", "X throws the ball", "It's actually a run play"],
        correct: 1,
        why: "A fakes like he's blocking the corner, then releases up the sideline on a wheel — that's the gadget.",
      },
      {
        q: "When should A look back for the ball on the wheel?",
        options: ["Immediately off the line", "Not until he's about 10 yards upfield", "Never, it's a decoy", "As soon as he beats the corner"],
        correct: 1,
        why: "Look too early and you'll slow down or tip the route — sell the fake, then find the ball.",
      },
      {
        q: "If the defense is playing tight and you need a chunk play, which combo does the QB lean on?",
        options: ["The deep combo on the left", "The RB dump-off", "Always the wheel route", "The hitch to X"],
        correct: 0,
        why: "The deep left combo is the called shot when you need more yardage.",
      },
    ],
  },
  {
    id: "virginia",
    unit: 2,
    unitName: "Shot Plays",
    category: "long",
    name: "Virginia",
    nickname: "Four verticals, pick your guy",
    icon: "🚀",
    formation: "normal",
    gist: "Everybody just runs. Virginia is four verticals — the QB's whole job is finding the best matchup and letting it fly deep.",
    assignments: [
      { pos: "X", text: "Outside release, run and look for the ball after 10-15 yards." },
      { pos: "B", text: "Inside release toward the hash marks, look for the ball after 10-15 yards." },
      { pos: "Y", text: "Mirror of X." },
      { pos: "A", text: "Mirror of B." },
      { pos: "F", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "One high safety? Work the outside guys (X or Y). Two high safeties? Work the inside guys (A or B). Either way — find the best matchup and throw it up.",
    routes: [
      { pos: "X", type: "go", dir: -1 },
      { pos: "B", type: "seam", dir: -1 },
      { pos: "Y", type: "go", dir: 1 },
      { pos: "A", type: "seam", dir: 1 },
    ],
    quiz: [
      {
        q: "There's one high safety. Who does the QB work?",
        options: ["The outside guys, X or Y", "The inside guys, A or B", "Only the RB", "Nobody, it's a run check"],
        correct: 0,
        why: "One high safety means he can't help outside — that's where the QB should look.",
      },
      {
        q: "There are two deep safeties. Who does the QB work?",
        options: ["The outside guys", "The inside guys, A or B", "He should throw it away", "The tight end only"],
        correct: 1,
        why: "With two safeties splitting the field, the inside seams have the better one-on-one.",
      },
      {
        q: "How many receivers are running vertical routes on this play?",
        options: ["Two", "Three", "Four", "One"],
        correct: 2,
        why: "It's called four verticals for a reason — X, B, A, and Y are all going.",
      },
    ],
  },

  // ---------------- UNIT 3: TRIPS & TRICK PLAYS ----------------
  {
    id: "verizon",
    unit: 3,
    unitName: "Trips & Trick Plays",
    category: "trips",
    name: "Verizon",
    nickname: "Four verticals out of trips",
    icon: "🎯",
    formation: "tripsRight",
    gist: "Same idea as Virginia, but out of a bunched-up trips look — three receivers stacked to one side. Everybody still just runs.",
    assignments: [
      { pos: "X", text: "Alone on the backside. Outside release, go get it after 10-15 yards." },
      { pos: "B", text: "Release toward the middle of the field, then turn it up straight once you're there." },
      { pos: "A", text: "Release toward the hash, then turn it up straight once you get there." },
      { pos: "Y", text: "Outside guy in the trips bunch — outside release, go get it deep." },
      { pos: "F", text: "Pass protect. Lobo or Robin call." },
    ],
    readKey: "If there's a favorable one-on-one on X by himself, just throw it to him. Otherwise, read the safeties — they've got to pick who they leave open.",
    routes: [
      { pos: "X", type: "go", dir: -1 },
      { pos: "B", type: "seam", dir: 1 },
      { pos: "A", type: "seam", dir: 1 },
      { pos: "Y", type: "go", dir: 1 },
    ],
    quiz: [
      {
        q: "X is singled up on the backside with a great matchup. What does the QB do?",
        options: ["Ignore it and work the trips side", "Just throw it to X", "Automatically throw it away", "Check to a run"],
        correct: 1,
        why: "A favorable 1-on-1 on the lone receiver is money — take it.",
      },
      {
        q: "How is Verizon different from Virginia?",
        options: ["It's a run play", "It's four verticals out of a trips (bunched) formation", "It only has two receivers", "There's no QB read"],
        correct: 1,
        why: "Same vertical concept, just packaged out of trips instead of a balanced formation.",
      },
      {
        q: "On Verizon, what do the safeties have to do?",
        options: ["Nothing, they're not involved", "Choose who they're willing to leave open", "Always double X", "Blitz every time"],
        correct: 1,
        why: "With four guys going deep, the safeties can't cover everybody — someone's getting left open.",
      },
    ],
  },
  {
    id: "pacific",
    unit: 3,
    unitName: "Trips & Trick Plays",
    category: "trips",
    name: "Pacific",
    nickname: "Three levels, pick your poison",
    icon: "🎯",
    formation: "tripsRight",
    gist: "Pacific stacks three different depths on the same side — short, medium, deep — so there's always something open no matter what the defense gives up.",
    assignments: [
      { pos: "X", text: "Alone on the backside. Dig across the middle at 10 yards." },
      { pos: "B", text: "The quickest route on the play — a 2-3 yard out. Get it out fast." },
      { pos: "A", text: "7-yard vertical release, then bend it to the pylon — corner." },
      { pos: "Y", text: "Outside guy — vertical release, look for the ball deep." },
      { pos: "F", text: "Pass protect. Lobo or Robin call — could sprint out too." },
    ],
    readKey: "Three levels stacked on top of each other: something short, something in the middle, and a shot deep. Take whatever the defense gives up, top to bottom.",
    routes: [
      { pos: "X", type: "dig", dir: -1 },
      { pos: "B", type: "out", dir: 1, depth: 3, quick: true },
      { pos: "A", type: "corner", dir: 1 },
      { pos: "Y", type: "go", dir: 1 },
    ],
    quiz: [
      {
        q: "What's the whole idea behind Pacific?",
        options: ["Everybody blocks", "Stacking three depths so something's always open", "It's a screen pass", "Only the deep ball matters"],
        correct: 1,
        why: "Short, medium, deep — the defense can't take away all three levels at once.",
      },
      {
        q: "Which route is the fastest one out on Pacific?",
        options: ["X's dig", "B's quick out", "A's corner", "Y's go route"],
        correct: 1,
        why: "B's route is only 2-3 yards — it's designed to get out in a hurry.",
      },
      {
        q: "Where does X line up on Pacific?",
        options: ["Bunched with the trips", "Alone on the backside", "In the backfield", "Next to the tackle"],
        correct: 1,
        why: "X is the lone receiver away from the trips bunch.",
      },
    ],
  },
  {
    id: "torch",
    unit: 3,
    unitName: "Trips & Trick Plays",
    category: "trips",
    name: "Torch",
    nickname: "The old razzle-dazzle",
    icon: "🎭",
    formation: "normal",
    gist: "Torch is the trick play of the bunch. It looks like a run to the slot, but the running back is actually about to throw it downfield. Total gadget football.",
    assignments: [
      { pos: "X", text: "10-yard square-in — a dig route." },
      { pos: "B", text: "5-yard crossing route. Also doubles as the backup safety valve for the RB." },
      { pos: "Y", text: "Stalk block first — sell it like a run — then release deep once the DB bites on the fake." },
      { pos: "A", text: "Seal the edge. Keep the defensive end from crashing outside and blowing the whole thing up." },
      { pos: "F", text: "You're the passer now. Get depth, square your shoulders, and sell the run before you even think about throwing. If Y or A aren't open, tuck it and run — or just chuck it away." },
    ],
    readKey: "The QB options it to the RB. From there, the RB (F) is running the whole show — sell the run, then find Y or A downfield.",
    routes: [
      { pos: "X", type: "dig", dir: -1 },
      { pos: "B", type: "cross", dir: -1 },
      { pos: "Y", type: "go", dir: 1, stalk: true },
      { pos: "A", type: "seal", dir: 1 },
      { pos: "F", type: "loopFlat", dir: 1 },
    ],
    quiz: [
      {
        q: "Who actually throws the ball on Torch?",
        options: ["The QB", "The RB (F)", "X", "Nobody, it's a designed run"],
        correct: 1,
        why: "The QB options it to the RB, who becomes the passer once he clears the line.",
      },
      {
        q: "What does Y need to do before releasing on his route?",
        options: ["Nothing, just run", "Sell the block like it's a real run play first", "Line up in the backfield", "Throw a block on the safety only"],
        correct: 1,
        why: "Y has to stalk block and sell the fake before the DB will bite and open up the route.",
      },
      {
        q: "If nobody's open, what's the RB's job?",
        options: ["Force a throw no matter what", "Tuck it and run, or throw it away", "Take a knee", "Lateral it to X"],
        correct: 1,
        why: "Same rule as always — if it's not there, protect the ball. Run it or chuck it away.",
      },
    ],
  },
];
